import Image from "next/image";

const HeroSection = () => {
    return (
        <section className="min-h-screen pt-24 pb-0 border-b border-border">
            {/* Top bar */}
            <div className="container mx-auto px-6">
                <div className="flex items-center justify-between py-6 border-b border-border">
                    <span className="label-mono">AI Image Generation</span>
                    <span className="label-mono">Est. 2026</span>
                </div>
            </div>

            {/* Main hero content - asymmetric */}
            <div className="container mx-auto px-6 pt-16 pb-20">
                <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-end">
                    {/* Left: massive headline */}
                    <div className="lg:col-span-7">
                        <h1 className="text-6xl sm:text-7xl lg:text-[6.5rem] font-extrabold leading-[0.9] tracking-tighter text-foreground">
                            YOUR
                            <br />
                            WORDS
                            <br />
                            <span className="text-primary">BECOME</span>
                            <br />
                            ART.
                        </h1>
                    </div>

                    {/* Right: description + image */}
                    <div className="lg:col-span-5 flex flex-col gap-8">
                        <div className="border-l-2 border-primary pl-6">
                            <p className="text-secondary-foreground text-lg leading-relaxed font-light">
                                Stop imagining. Start generating. PixGen turns raw text into cinematic visuals — no templates, no limits, no creative ceiling.
                            </p>
                        </div>

                        <div className="overflow-hidden">
                            <Image
                                src="/gallery-1.png"
                                alt="Cyberpunk portrait generated by PixGen AI"
                                width={500}
                                height={625}
                                className="w-full aspect-[4/5] object-cover grayscale hover:grayscale-0 transition-all duration-700"
                            />
                        </div>
                    </div>
                </div>
            </div>

            {/* Marquee ticker */}
            <div className="bg-primary text-primary-foreground py-3 overflow-hidden">
                <div className="marquee-track whitespace-nowrap flex gap-8">
                    {Array.from({ length: 2 }).map((_, i) => (
                        <span key={i} className="flex gap-8 text-sm font-bold uppercase tracking-widest">
                            <span>Text to Image</span>
                            <span>·</span>
                            <span>4K Upscaling</span>
                            <span>·</span>
                            <span>30+ Styles</span>
                            <span>·</span>
                            <span>Commercial License</span>
                            <span>·</span>
                            <span>Under 5 Seconds</span>
                            <span>·</span>
                            <span>500K+ Creators</span>
                            <span>·</span>
                            <span>Text to Image</span>
                            <span>·</span>
                            <span>4K Upscaling</span>
                            <span>·</span>
                            <span>30+ Styles</span>
                            <span>·</span>
                            <span>Commercial License</span>
                            <span>·</span>
                            <span>Under 5 Seconds</span>
                            <span>·</span>
                            <span>500K+ Creators</span>
                            <span>·</span>
                        </span>
                    ))}
                </div>
            </div>

            {/* Full-width hero image */}
            <div className="w-full">
                <Image
                    src="/hero-image.png"
                    alt="AI-generated fantasy landscape by PixGen"
                    width={1920}
                    height={600}
                    className="w-full h-[50vh] object-cover"
                    priority
                />
            </div>
        </section>
    );
};

export default HeroSection;
